### ISSUE TITLE
Table of contents placed in the wrong place (#1)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#10]
Hi Ao,

Your table of contents section should be in front of revision history and reference materials.

**Comment by Ao99** [comment]
In the two different templates - SRS and CA, the table of contents are placed at different locations.
That's why people writing CA all put it as I do.
@smiths 
Where do you want it to be?

**Comment by Ao99** [comment]
It'll keep unchanged unless Prof. Smith thinks otherwise.

**Comment by smiths** [comment]
I should standardize this for next year, but it is fine they way it currently is for this year.
