### ISSUE TITLE
2nd paragraph of Purpose of Document redundancy(#2)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#11]
Hi Ao,

I think the second paragraph of Purpose of Document can be removed because we are only focusing on the SRS, and I feel like it's unnecessary to talk about the next steps. But I'm not so sure about this though. @smiths  What do you think?

**Comment by Ao99** [comment]
Personally I don't think it should be removed. It'll keep unchanged unless Prof. Smith thinks otherwise.

**Comment by smiths** [comment]
I like the way the purpose of the document is presented.  @Ao99, you can leave it as it is.
