### ISSUE TITLE
organization of document(#3)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#12]
Hi Ao,

In the Organization of Document, you used the word "The presentation follows the standard pattern", did you mean The document?

**Comment by Ao99** [comment]
The phrase is borrowed from Drasil projects.
I think it means the presentation of this document.

**Comment by smiths** [comment]
Yes, the word presentation to stand in for "presentation of this document" is fine.  You can leave it as is.
