### ISSUE TITLE
lack of introduction in requirements part(#4)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#13]
Hi Ao,

In the Requirements section, you didn't provide introduction in Functional Requirements and Nonfunctional Requirements part. I think it will be better to add introduction such as "This section provides the functional requirements, the tasks and behaviours that the software is expected to complete." for Functional Requirements, and "This section provides the non-functional requirements, the qualities that the software is expected to exhibit.".

**Comment by Ao99** [comment]
These words actually have been there, at 7 Requirements (not 7.1 nor 7.2).
