### ISSUE TITLE
Reference number is missing(#5)

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#14]
Hi Ao,

I think it might be more clear if you add numbers to your references, like this: 
 **[1]** Web Caching project. http://www.ircache.net.
**[2]** Intel Outlines Platform Innovations for More Manageable, Balanced and
Secure Enterprise Computing. Intel Press Release, February 2004.
http://www.intel.com/ca/pressroom/2004/0218b.htm.
**[3]** T. Abdelzaher, K. G. Shin, and N. Bhatti. Performance guarantees for Web
server end-systems: A control-theoretical approach. IEEE Transactions on
Parallel and Distributed Systems, 13(1), 2002.
**[4]** B. D. O. Anderson and J. B. Moore. Optimal Control: Linear Quadratic
Methods. Prentice Hall, 1989.

**Comment by Ao99** [comment]
Again, I was just following the template.
@smiths 
What's your preference?

**Comment by Ao99** [comment]
It'll keep unchanged unless Prof. Smith thinks otherwise.

**Comment by smiths** [comment]
The references look fine to me.
