### ISSUE TITLE
VnV Issue#1 Spelling mistake 

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#19]
Hi Ao,

I think you meant "plan" here in section 4.3 Design Verification Plan. 
<img width="560" alt="Screen Shot 2019-10-29 at 10 59 33 PM" src="https://user-images.githubusercontent.com/55267358/67825475-ce560a00-fa9f-11e9-9159-82709af1ddee.png">

**Comment by Ao99** [comment]
Revised
