### ISSUE TITLE
VnV Issue#2 missing reference to section

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#20]
Hi Ao,

 
In section 4.4, you forgot to give reference. 
<img width="566" alt="Screen Shot 2019-10-29 at 11 02 34 PM" src="https://user-images.githubusercontent.com/55267358/67825640-5b995e80-faa0-11e9-97d7-b0bdcec1e422.png">

**Comment by Zhang-Zhi-ZZ** [comment]
Same issue in the later part of section 4.4. 

<img width="559" alt="Screen Shot 2019-10-29 at 11 08 24 PM" src="https://user-images.githubusercontent.com/55267358/67825851-0e69bc80-faa1-11e9-80a6-6db6be1103d5.png">

**Comment by Ao99** [comment]
revised
