### ISSUE TITLE
VnV Issue#3 Specify the technique you will use?

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#21]
Hi Ao,

In section 4.4, you used the phrase "some static code analyzer can be used", but I think it's better to specify which code analyzer you will use for the automatic testing. But I'm not so sure about this. 

@smiths  What do you think?

<img width="566" alt="Screen Shot 2019-10-29 at 11 04 53 PM" src="https://user-images.githubusercontent.com/55267358/67825765-c9de2100-faa0-11e9-8eef-aa627231eceb.png">

**Comment by smiths** [comment]
@best-zhang-zhi, yes, we should be specific about what code analyzer.  @Ao99, you should decide your language of implementation and then select an appropriate tool for static analysis.

**Comment by Ao99** [comment]
The code analyzers are already in the picture, PMD, LGTM, and Deep Dive.
I didn't specify which of the three to use because I would like to provide more flexibility.
