### ISSUE TITLE
VnV Issue#4 Missing reference to data constraints table

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#22]
Hi Ao,

In section 5.1.1, the input verification part, you may need to add reference to your data constraints table in your CA as Dr. Smith mentioned in the blank project VnV template. 

<img width="430" alt="Screen Shot 2019-10-29 at 11 17 07 PM" src="https://user-images.githubusercontent.com/55267358/67826315-7b318680-faa2-11e9-80ab-e385e21b0079.png">

**Comment by Ao99** [comment]
CA doesn't have data constraints.

But since I've changed my CA to SRS, I added it here.
