### ISSUE TITLE
VnV Suggestion: Design Verification Plan Is Too High Level

### ISSUE THREAD

**Issue by sorainsm** [Ao99/CAS741#24]
Hi Ao,

I think you should be more specific about _how_ you're going to verify your design (e.g. the techniques that you're going to use). I think everything you say in this section is correct; however, from reading it I can't tell how you intend to check that your design is correct to the problem that it's addressing.

I'd suggest something like a peer review with specific tasks. For example, you might give one of your peers (i.e. me) a particular requirement and ask me to do a system review to see if the structure of the system meets that requirement.

![image](https://user-images.githubusercontent.com/11723492/68720728-37e51680-057e-11ea-8c47-b00180550e54.png)

**Comment by sorainsm** [comment]
You specifically look to test the system design through the test case of #30 
This is one of the things you can state as a specific technique being used in design verification.

**Comment by smiths** [comment]
@sorainsm, I made a similar comment in my review.  I also added the feedback that @Ao99 could look to the VnV plan of @peter-michalski, since @peter-michalski had some nice specifics mapped out in his design verification.

**Comment by Ao99** [comment]
I borrowed and cited the ideas from both Peter and Sasha
