### ISSUE TITLE
VnV Review: Test case execution needs to be more specific

### ISSUE THREAD

**Issue by sorainsm** [Ao99/CAS741#25]
Hi Ao,

I think that your _How test will be performed_ sections are too abstract.
If I was handed this document, I wouldn't be sure how to proceed.

I think it would be more clear if you specifically list one particular input, and a list of steps for how the test will be performed.

For example, using the test case below - I would instead have:
Input: invalid.txt
...
How Test Will Be Performed: Tester will select input (invalid.txt) for the system and begin processing. System will display input error message.

I don't think this needs to be repeated with multiple file extensions - you've stated that your system only works with .dcm and .dcm30, so having .txt or .pdf (not both) would count as representative of "not valid inputs". @smiths your opinion on this would be appreciated!

![image](https://user-images.githubusercontent.com/11723492/68721277-dde55080-057f-11ea-9d40-c2bc6dc41044.png)

**Comment by smiths** [comment]
I agree @sorainsm.  I made similar observations in my review in commit c935b3f.  @Ao99, I think you like the idea of leaving some decisions open, but it is better to make the decision now, and "fake" the documentation later, if you change your mind.

**Comment by Ao99** [comment]
Modified to automatic control with JUnit test.
