### ISSUE TITLE
VnV Suggestion: Conceptually Separate Display from Calculation

### ISSUE THREAD

**Issue by sorainsm** [Ao99/CAS741#26]
Hi Ao,

I think that the test cases under Calculation Test are combining testing the calculation of the thresholds and displaying of the thresholds.

Testing the calculation of this information would be performed as a unit test - to verify that the output of your calculation matches what the final value should be. This is where JUnit comes in.

Displaying the output is a system behaviour that would be captured in this System VnV Plan.  

I think you understand this because you say in the Test Case Derivation that it displays "potentially correct number of values" which is really what the test ought to be.

To make this separation more clear I think you should relabel this section Output Display Testing, and remove information about JUnit from the _How Test Will Be Performed_ section.

![image](https://user-images.githubusercontent.com/11723492/68721860-cb6c1680-0581-11ea-8781-7363c8fd65dd.png)

**Comment by Ao99** [comment]
As for this software, the display part is very straight forward. I don't think that it needs to be tested separately. I'll keep it unchanged for now, and reconsider it later.
