### ISSUE TITLE
LaTeX Suggestion: Quotation Marks

### ISSUE THREAD

**Issue by sorainsm** [Ao99/CAS741#27]
Hey Ao, 

Noticed there were some issues with your quotation marks.
When typing quotation marks into LaTeX you should use backticks ( ` ` ) as your left quotation mark and apostrophes as your right quotation marks ( ' ' ) - this will ensure that the quotation marks build correctly.

![image](https://user-images.githubusercontent.com/11723492/68723155-c27d4400-0585-11ea-844d-75404c69bdf8.png)

**Comment by smiths** [comment]
@Ao99, I fixed the quotes around reasonably in commit c935b3f.  You should search the document though to see if there are any other uses of `"`.  I also mean that you should literally use the search feature of your text editor.  You don't need to do this kind of search by eye.

**Comment by Ao99** [comment]
Adjusted.
