### ISSUE TITLE
VnV Review: Be Specific in External Software Being Used in Testing

### ISSUE THREAD

**Issue by sorainsm** [Ao99/CAS741#28]
Similar to issue #21

I think it's a great idea using an external software to check for this.
However, I think you should be explicit here about what specifically you're using and how a tester should use it.

For example, if  you are using checkfiletype.com then it would be a **manual** test with the following steps:
1. Tester loads checkfiletype.com
2. Tester clicks browse and locates the output file
3. Tester clicks check file type
4. Tester visually verifies that file type is X

![image](https://user-images.githubusercontent.com/11723492/68723441-91514380-0586-11ea-9e4c-2f9d07652256.png)

**Comment by sorainsm** [comment]
Similar issue applies to the correctness output file test case: 

![image](https://user-images.githubusercontent.com/11723492/68723694-500d6380-0587-11ea-8da5-1098aae63324.png)

**Comment by Ao99** [comment]
You're right, we can use some external software or tools. However, after the implementation of the code, I realized that it might be easy to do the test with some Java image-reading library and JUnit.
