### ISSUE TITLE
VnV Review: Test Cases Should be Standalone

### ISSUE THREAD

**Issue by sorainsm** [Ao99/CAS741#29]
Related to #25 

The test cases should be standalone - meaning we should be able to read each of them individually without needing to reference a different test case.

It would be better if the installability test cases had something more specific than "as above" in their execution steps - even if it's identical.

![image](https://user-images.githubusercontent.com/11723492/68723812-bf835300-0587-11ea-8cb1-bdcd1016b3cf.png)

**Comment by smiths** [comment]
Yes, "as above" is a bit ambiguous, but we also don't want to continually repeat the same text.  Often the problem can be solved by introducing a table that contains the deltas between the tests.  In this case a more specific pointer might do the trick.  (not just saying "as above", but spelling out where the instructions are to be found.)

**Comment by Ao99** [comment]
Adjusted.
