### ISSUE TITLE
VnV Review: Add MG and MIS to Relevant Documentation

### ISSUE THREAD

**Issue by sorainsm** [Ao99/CAS741#30]
The module guide and module interface specification are listed as part of the understandability test case (see below).

![image](https://user-images.githubusercontent.com/11723492/68723959-30c30600-0588-11ea-9bcd-f0533248bfe9.png)

They should then be similarly added to the relevant documentation at the beginning of the document. 

![image](https://user-images.githubusercontent.com/11723492/68724003-54864c00-0588-11ea-9d26-473a8224ceef.png)

**Comment by smiths** [comment]
I agree with @sorainsm.  I made the same comment in my review (commit c935b3f).

**Comment by Ao99** [comment]
Adjusted.
