### ISSUE TITLE
VnV Question: Unclear How R2 is being met by 5.1.4

### ISSUE THREAD

**Issue by sorainsm** [Ao99/CAS741#31]
Hi Ao,

According to the traceability matrix, R2 (resolution) is being tested by 5.1.4. (Output Verification)

![image](https://user-images.githubusercontent.com/11723492/68724203-d24a5780-0588-11ea-8a46-930b1a88d9b3.png)

From the current description of 5.1.4. (see below), it's not clear to me how the resolution is being checked. The provided link shows us the file type but not the resolution of the output image.

I think that this might need to be split up into 2 tests - 1 to check the file type, and one to check the resolution.

![image](https://user-images.githubusercontent.com/11723492/68724333-26edd280-0589-11ea-81ed-4a792d06fca8.png)

**Comment by sorainsm** [comment]
I think addressing #28 and #25 would clear this up.

**Comment by smiths** [comment]
@sorainsm, I really like your issues.  They are nicely self-contained and easy to follow.

**Comment by Ao99** [comment]
Adjusted.
I made it more specific that it will be performed by the test team with the help of JUnit and OpenCV Java library.
