### ISSUE TITLE
Please implement module 12

### ISSUE THREAD

**Issue by Ao99** [Ao99/CAS741#36]
Please implement module 12 - Image Verification in my MIS in Java.

It should be a simple task, the module only test the size and pixel values of a single image, and compare the sizes of two images.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Ao, 
I have implemented module 12 in commit: c679205961b7521fcba98756bbe4d3cb02257094.
Please let me know if there's any issue^_^

**Comment by Ao99** [comment]
Thank you :)
I will take a look later~
