### ISSUE TITLE
MG issue 2 Grammar and wording

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#38]
Missing a space between **is more** 
![Screen Shot 2019-11-28 at 6 19 34 PM](https://user-images.githubusercontent.com/55267358/69834949-bb079d00-120b-11ea-8244-089e1f9cb272.png)

**Comment by Zhang-Zhi-ZZ** [comment]
![Screen Shot 2019-11-28 at 6 34 28 PM](https://user-images.githubusercontent.com/55267358/69835201-bba13300-120d-11ea-81d9-350a48bcd306.png)
same issue here

**Comment by Zhang-Zhi-ZZ** [comment]
![Screen Shot 2019-11-28 at 6 36 36 PM](https://user-images.githubusercontent.com/55267358/69835240-091da000-120e-11ea-9c65-4295baa8467f.png)
should capitalize the V

**Comment by Ao99** [comment]
Thanks. Modified.
