### ISSUE TITLE
Functional Requirements - system requirements, not user.

### ISSUE THREAD

**Issue by peter-michalski** [Ao99/CAS741#4]
Functional requirements are supposed to define requirements for the system, not the user. 

Some of the functional requirements listed are requirements of the user; if you want these then they should go into another section like assumptions (if they can be logically placed there) otherwise they do not need to go into the SRS/CA report from the perspective of the user. For example, it can be assumed that the user intends to enter correctly formatted/appropriate input. However, what if they do not? The functional requirements, from a system perspective, should take care of input errors (as you have already done with R4 - which is good)

The FR's should be only be something like "the system shall/will etc."  (logically, not verbatim)

Essentially, my comment is directed specifically at R1 and R3. Your R1 and R3 are not supposed to be here, since you are stating what the user should do and not the system. R3 can be removed. R1 is already covered from a system functional requirements perspective in R4.

**Comment by Ao99** [comment]
I agree, good suggestion.
Revised.
