### ISSUE TITLE
MIS ISSUE 3

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [Ao99/CAS741#42]
Hi Ao. 
in section 6.3.2, you included 3 exceptions, but I think these exceptions should go to other modules, for example, the emptyloadedImage should be the exception in Input Module. You can refer to the MIS for SWHS, that's also how they did it. 

In my understanding, main is just a frame of your program, all the exceptions should be considered in functions of the main.

**Comment by Ao99** [comment]
I agree with you. I found out during implementation that it might be good to put them into specific modules.
