### ISSUE TITLE
Hard to read

### ISSUE THREAD

**Issue by sharyuwu** [Ao99/CAS741#45]
![image](https://user-images.githubusercontent.com/55363335/70762874-36933f00-1d20-11ea-9da3-bf5b610b56e3.png)

This possible is hard to read. It seems like it includes lots of changes inside.
Suggest to break it down to maybe 2 changes like 1. global/local 2. 2 thresholds/ multiple thresholds.

**Comment by Ao99** [comment]
We're recommended to not do that. One likely change to one module.
