### ISSUE TITLE
Word choice

### ISSUE THREAD

**Issue by sharyuwu** [Ao99/CAS741#46]
![image](https://user-images.githubusercontent.com/55363335/70762990-9c7fc680-1d20-11ea-97de-65eb261173a4.png)

I feel using the word "Generation" it a bit weird here. By "Generation", it sounds like you are just going to generate one of the versions in this table. If you will generate all 3 different versions of images, maybe "Output" can be a better word choice.

**Comment by Ao99** [comment]
"Generation" means something else here. Such as "The first generation", "A generation of people".
