### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by sharyuwu** [Ao99/CAS741#48]
Found some spacing issue when I go through the document:)
![image](https://user-images.githubusercontent.com/55363335/70763654-d5209f80-1d22-11ea-918d-5adadc1147c9.png)
![image](https://user-images.githubusercontent.com/55363335/70763678-ebc6f680-1d22-11ea-9400-6d3962a679eb.png)

**Comment by Ao99** [comment]
Modified. Thank you.
