### ISSUE TITLE
Is this an abstract data type

### ISSUE THREAD

**Issue by sharyuwu** [Ao99/CAS741#49]
![image](https://user-images.githubusercontent.com/55363335/70763864-9f2feb00-1d23-11ea-8aa3-eea0dbf291b2.png)

Since this module is input something and then output itself(ImageData), is it actually an abstract data type?

**Comment by Ao99** [comment]
Yes, it is. I don't quite understand what you're trying to suggest here.

**Comment by smiths** [comment]
@Ao99, I believe @sharyuwu is pointing out that your module follows the template for an abstract object, when you want to be following the template for an abstract data type.  There are some differences between abstract objects and ADTs in the template.  For instance, ADTs export the type, with a question mark, and the word "template" is incorporated into the heading.

**Comment by sharyuwu** [comment]
@smiths 
Yes, that is what I am trying to address here. 
Thank you for clarifying my statement.

**Comment by Ao99** [comment]
Changed the format to this [example](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/blob/master/Assignments/A2/A2.pdf)
