### ISSUE TITLE
DD5 equation

### ISSUE THREAD

**Issue by peter-michalski** [Ao99/CAS741#9]
DD5 equation is L=2^n

Yes, the L value in this project is always 256 based on A2, but the equation is still L=2^n

**Comment by Ao99** [comment]
I didn't use 2^n because I wanted my IM to use the number 256 directly. I have to think about this one later.

**Comment by smiths** [comment]
@Ao99,  you can combine your approach and the suggestion by @peter-michalski.  You can use the equation, and then say the valid potential values for n.  You don't have to have the type of n be all natural numbers.  The type can be [1..4] (or whatever you are working with).
